### ISSUE TITLE
EVIOCGRAB failed with error 16

### ISSUE THREAD

**Issue by Makkaan** [irtimmer/moonlight-embedded#241]
Hello!

I've been trying the last few days to install OSMC with Moonlight.

I get the popup to pair the machines but i get this error after that:
Can't open configuration file: hosts/192.168.1.13.conf
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...RTSP message too long
RTSP DESCRIBE request failed: -1
failed: -1
EVIOCGRAB failed with error 16
EVIOCGRAB failed with error 16
EVIOCGRAB failed with error 16

And when i try on my old pc i get this:

Can't open configuration file: hosts/192.168.1.206.conf
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM sysdefault
Alsa error code -2

**Comment by TallyTalman** [comment]
I had the exact same problem concerning the RTSP handshake failing.

Looks like this is a Nvidia related issue.

I found this program: http://www.guru3d.com/files-details/display-driver-uninstaller-download.html
It uninstalled everything Nvidia related properly in Safe Mode. For your own convenience I advise you download the driver beforehand from the official Nvidia site, so once have uninstalled everything and you get back from safe mode, all you have to do is run the installer.

This fixed the same problem immediately for me (I was messing around way to long, because I didn't realize my previous attempt to reinstall Nvidia was insufficient).

Cannot help you with your problem regarding the old PC, because most of this stuff goes way over my head, but I hope this helps you get past the RTSP handshake on your main machine, like it did for me. Good luck.

**Comment by cgutman** [comment]
This is a duplicate of #245

**Comment by irtimmer** [comment]
Fixed with @48f88f6d2fb2fe4a4bbd800cbbd8332e09b73a0d

**Comment by diegombeltran** [comment]
Still not working, using last OSMC packages and Moonlight-Embedded 2.1.2 from Jessie repo
